sudo: true
language: c
compiler:
    - gcc
install: 
    - sudo apt-get install gawk wget
    - mkdir sources
    - wget --input-file=wget-list --continue --directory-prefix=./sources
    - pushd sources && md5sum -c ../md5sums && popd
test: true
script: true
